services:
  app:
    container_name: swu_app
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@host.docker.internal:5470/${POSTGRES_DB}
      - JWT_SECRET=${JWT_SECRET}
    volumes:
      - ./uploads:/app/uploads